# Generated by Django 4.0.3 on 2022-04-29 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_mealplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(related_name='recipe', to='recipes.recipe'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealplan', to=settings.AUTH_USER_MODEL),
        ),
    ]
