# Generated by Django 4.0.3 on 2022-04-29 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_recipe_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mealplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('recipes', models.ManyToManyField(related_name='recipes', to='recipes.recipe')),
                ('user', models.ManyToManyField(related_name='MealPlan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
