# Generated by Django 4.0.3 on 2022-05-02 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_shopping_item_delete_mealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_item',
            name='food_item',
        ),
        migrations.AddField(
            model_name='shopping_item',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FoodItem', to='recipes.fooditem'),
        ),
        migrations.AlterField(
            model_name='shopping_item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
